config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container mt-3">

  <div class="row">
    <div class="col-12">
      <h2>All our Flats(<%= @flats.length %>)</h2>
    </div>
  </div>

  <div class="row">
	    <% @flats.each do |flat| %>

        <div class="col-md-4">
          <div class="flat-card-image" style="background-image: url('<%= flat.picture_url %>')">
          </div>

          <div class="flat-card">
	          <div class="flat-card-content">
	            <div class="flat-card-title">
	              <h4><%= flat.name %></h4>
	            </div>

              <p><%= flat.address %></p>

              <div class="flex">
               <i class="fa-solid fa-camera-retro"></i> <%= flat.number_of_guests %>
               <div class="ms-3">
                  <i class="fa-solid fa-euro-sign"></i>  <%= flat.price_per_night %>
                </div>
              </div>
	          </div>

            <div class="flat-card-actions">
	            <%= link_to 'More info', flat_path(flat) %>
	            <%= link_to 'Edit', edit_flat_path(flat), class: 'ms-3 text-warning' %>
	            <%= link_to "Remove", flat_path(flat),
	                method: :delete,
	                data: { confirm: "Are you sure?" },
	                class: 'ms-3 text-danger'
	            %>
	          </div>

          </div>

        </div>

      <% end %>
	</div>

</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url('<%= @flat.picture_url %>')"></div>

<div class="container col-6 mt-3">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h4><%=@flat.name  %></h4>
        <p><%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <h5>A bit more about this flat</h5>
        <p> <%=@flat.description  %></p>
      </div>
    </div>

    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place</h5>
      </div>
      <div class="flat-show-card">
        <h4>Details</h4>
        <p><i class="fa-solid fa-camera-retro"></i> <%= @flat.number_of_guests %></p>
        <p><i class="fa-solid fa-euro-sign"></i>  <%= @flat.price_per_night %></p>
      </div>
       <div class="flat-show-card">
        <div class="flex-align">
          <h4>Share</h4>
          <div class="flex ">
            <h4><i class="fa-brands fa-facebook-square me-2"></i></h4>
            <h4><i class="fa-brands fa-instagram-square me-2"></i></h4>
          </div>
        </div>
       </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "Simple Airbnb", "#", class: "navbar-brand"%>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

          <li class="nav-item active">
            <%= link_to "Search", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add a flat", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

      <%= yield %>
  </body>
</html>